# Generated by Django 6.0.2 on 2026-02-16 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('target_role', models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('STAFF', 'Staff'), ('TRANSPORT_MANAGER', 'Transport Manager')], default='STUDENT', help_text='Who is this announcement for?', max_length=50)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
